title: Ryuto Setsujin
description: My portfolio site.
theme: just-the-docs

url: https://ryutosetsujin.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

plugins:
  - jemoji
  - jekyll-twitter-plugin
  - jekyll-youtube